name: Publish package to the Maven Central Repository
on: push
  #release:
    #types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: |
          echo $GPG_PRIV_KEY > secring.text
          gpg --import --batch secring.text
          echo "ossrhUsername=${ossrhUsername}" >> gradle.properties
          echo "ossrhPassword=${ossrhPassword}" >> gradle.properties
          echo "signing.keyId=${signingKeyId}" >> gradle.properties
          echo "signing.password=${signingPassword}" >> gradle.properties
          gradle -Prelease uploadArchives
        env:
          ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ossrhPassword: ${{ secrets.OSSRH_TOKEN }}
          signingKeyId: ${{ secrets.SIGNING_KEY_ID }}
          signingPassword: ${{ secrets.SIGNING_PASSWORD }}
          GPG_PRIV_KEY: ${{ secrets.GPG_PRIV_KEY }}